chore: auto deployment for renovate/dependabot PRs (#1065)

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -83,6 +83,13 @@ jobs:
           skip-commit: "true"
           skip-on-empty: "false"
           git-push: "true"
+      - name: Validate semantic version
+        run: |
+          if [ -z "${{ steps.changelog.outputs.version }}" ]; then
+            echo "Missing semantic version"
+            exit 1
+          fi
+          
   retag-images:
     needs: [vars, semantic-version]
     runs-on: ubuntu-24.04
@@ -131,11 +138,17 @@ jobs:
       backend-external-url: https://pay-transparency-dev-backend-external.apps.silver.devops.gov.bc.ca/api
 
   get-last-deployed-and-check-human:
+<<<<<<< HEAD
     if: vars.PR_AUTO_APPROVAL_ENABLED == 'true'
     name: Get Last Deployed Version & Check Human Changes
     needs: [semantic-version, deploys]
     runs-on: ubuntu-24.04
     environment: prod
+=======
+    name: Get Last Deployed Version & Check Human Changes
+    needs: [semantic-version, deploys]
+    runs-on: ubuntu-24.04
+>>>>>>> 8404608 (chore: auto deployment for renovate/dependabot PRs (#1065))
     permissions:
       actions: read
     outputs:
@@ -157,7 +170,11 @@ jobs:
         with:
           oc_namespace: db4642-prod
           oc_server: ${{ vars.oc_server }}
+<<<<<<< HEAD
           oc_token: ${{ secrets.OC_TOKEN }} 
+=======
+          oc_token: ${{ secrets.oc_token }} 
+>>>>>>> 8404608 (chore: auto deployment for renovate/dependabot PRs (#1065))
           commands: | 
              oc project db4642-prod
 
